[package]
name = "kOS"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "lib/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
